POST http://localhost:8080/volunteer/add
Content-Type: application/json

{
  "name": "Rahaf",
  "email": "rb3713@columbia.edu",
  "hashedPassword": "rahaf123",
  "age": 25,
  "address": "116st ny",
  "phone": "+19294288888"
}




